Remove SAV token whitelist mode and remove SAVR token whitelist mode disable
iSaver-io/isaver-contracts pull request #36
Opened 2023-07-25 13:08 UTC by GolubevDS

2023-07-29 13:41 UTC, nikitaGetman requested changes

2023-07-29 13:41 UTC, nikitaGetman commented on contracts/tokens/BasicToken.sol
> -import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Snapshot.sol";
Добавь заодно функциональность снапшотов в BasicToken. Можно добавить отдельную роль SNAPSHOT_CREATOR_ROLE, или что то типа того

2023-07-29 13:41 UTC, nikitaGetman commented on contracts/tokens/Token2.sol
> +            _removeFromWhiteList(addresses);
Тут было Whitelist для консистентности с Blacklist. Если хочешь использовать WhiteList, то Blacklist давай тоже поменяем везде на BlackList

2023-08-02 12:09 UTC, nikitaGetman requested changes

2023-08-02 12:09 UTC, nikitaGetman commented on contracts/tokens/Token2.sol
> +        if (isWhitelistRestrictionMode) {
Белый список отключить нельзя. Поэтому данный флаг не нужен.
Из контракта WhiteList тоже нужно его удалить

2023-08-02 12:09 UTC, nikitaGetman commented on contracts/tokens/Token2.sol
> +                whiteList[from] || whiteList[to],
Можно заменить на isAddressInWhiteList

2023-08-04 11:19 UTC, nikitaGetman requested changes

2023-08-04 11:19 UTC, nikitaGetman commented on contracts/tokens/Token2.sol
>      }
Можно вызвать конструктор BasicToken с  `initialSupply_ = 0`, а после добавления адресов в БС добавить `_mint(holderAddress_, initialSupply_);`

2023-08-04 11:19 UTC, nikitaGetman commented on contracts/tokens/Token2.sol
> +        if (totalSupply() != 0) {
Тогда эта проверка будет не нужна

2023-08-10 12:20 UTC, nikitaGetman requested changes

2023-08-10 12:20 UTC, nikitaGetman commented on contracts/tokens/Token2.sol
> +        require(isAddressInWhiteList(to), "WhiteList: receiver is not in whiteList");
Тут достаточно, чтобы либо отправитель, либо получатель были в БС. Чтобы пользователи могли отправлять токены контракту, который в БС (сами пользователи не обязательно должны быть в БС)

2023-08-10 13:22 UTC, GolubevDS commented on contracts/tokens/Token2.sol
> +        require(isAddressInWhiteList(to), "WhiteList: receiver is not in whiteList");
Поправил

2023-08-11 11:11 UTC, nikitaGetman approved these changes

2023-08-11 12:10 UTC, merged