Removed manually set of lottery winners
iSaver-io/isaver-contracts pull request #38
Opened 2023-07-31 06:08 UTC by GolubevDS

2023-08-02 12:52 UTC, nikitaGetman requested changes

2023-08-02 12:52 UTC, nikitaGetman commented on contracts/Lottery.sol
Давай переименуем manuallyGetWinners в getWinnersFromOracleRandom

2023-08-05 11:57 UTC, GolubevDS commented on contracts/Lottery.sol
По этому ПРу всё готово

2023-08-10 12:28 UTC, nikitaGetman approved these changes

2023-08-10 12:28 UTC, nikitaGetman commented on contracts/Lottery.sol
> +                // winner ticket is from 1 to tickets.length
```suggestion
                // winner ticket is from 1 to totalRoundTickets
```

2023-08-10 13:16 UTC, merged