Add ContractRegistry contract
iSaver-io/isaver-contracts pull request #43
Opened 2023-08-20 13:32 UTC by GolubevDS

2023-08-21 14:47 UTC, nikitaGetman requested changes

2023-08-28 17:27 UTC, nikitaGetman requested changes

2023-08-28 17:27 UTC, nikitaGetman commented on contracts/ReferralManager.sol
>      mapping(address => bool) private authorizedContracts;
Логику с авторизацией контрактов тоже можно убрать. Вместо нее проверять адрес контракта отправителя транзакции, что он совпадает с адресом стейкинга или командного контракта (эти адреса брать из менеджера, только нужно учесть что отправляться транзакция из другого контракта может с адреса реализации а не прокси)

2023-09-08 09:41 UTC, GolubevDS commented on contracts/ReferralManager.sol
>      mapping(address => bool) private authorizedContracts;
Уберу логику с авторизацией на ПРе с тестами.
При работе с прокси uups делегация вызова происходит через delegatecall, то есть контекст должен сохраняться.
Так что с этим проблем быть не должно.

2023-09-08 13:15 UTC, nikitaGetman requested changes

2023-09-08 13:15 UTC, nikitaGetman commented on deploy/001_token1_deploy.ts
>  func.tags = ["Token1"];
Надо везде ContractManager_deploy в зависимости добавить )

2023-09-08 13:15 UTC, nikitaGetman commented on deploy/000_contract_manager_deploy.ts
> +export default func;
Можно добавить скрипт обновления, так как в будущем могут новые контракты появиться, их тоже в менеджер добавим

2023-09-08 13:54 UTC, merged