A contract has been created to work with the project's collection of avatars
iSaver-io/isaver-contracts pull request #46
Opened 2023-10-18 15:32 UTC by GolubevDS

2023-10-19 15:56 UTC, nikitaGetman requested changes

2023-10-19 15:56 UTC, nikitaGetman commented on contracts/tokens/ISaverAvatars.sol
> +        require(_attributesLength <= TOTAL_NFTs, "Exceeds max tokens");
Скорее всего так: `_attributesLength + _attributes.length <= TOTAL_NFTs`
Так как увеличится количество загруженных атрибутов

2023-10-19 15:56 UTC, nikitaGetman commented on contracts/tokens/ISaverAvatars.sol
> +                    '"image": "https://raw.githubusercontent.com/iSaver-io/isaver-dashboard/234ae4e0650dad6b6a9e5339b64823fec738a491/public/avatars/',
Давай описание, image и external_url вынесем в переменные. И добавим методы для их редактирования админом

2023-10-19 15:56 UTC, nikitaGetman commented on contracts/tokens/ISaverAvatars.sol
> +            memory json = '{"name": "iSaver Avatars","description":"Welcome to the home of iSaver Avatars on OpenSea. This is a collection of 12,024 avatars living on the Polygon blockchain. They cam
Тут тоже можно вынести значения в параметры, чтобы можно было настраивать

2023-10-19 15:56 UTC, nikitaGetman commented on contracts/tokens/ISaverAvatars.sol
> +    }
Давай по другому принципу разделим атрибуты, например одежда (влияющие на слои) и остальные параметры. Так как пока не все атрибуты будут изменяемыми

2023-10-19 16:00 UTC, nikitaGetman requested changes

2023-10-20 05:13 UTC, nikitaGetman commented
И добавь код генератора тоже )

2023-10-20 11:42 UTC, GolubevDS commented on tasks/avatars.ts
> +      fs.readFileSync(path.resolve(process.cwd(), "config/metadata/nft_attributes.json"), "utf8")
Закинул

2023-10-20 11:43 UTC, GolubevDS commented
> И добавь код генератора тоже )

2023-10-20 20:28 UTC, nikitaGetman requested changes

2023-10-20 20:28 UTC, nikitaGetman commented on tasks/avatars.ts
> +    console.log(taskArgs.description);
log

2023-10-20 20:28 UTC, nikitaGetman commented on contracts/tokens/ISaverAvatars.sol
> +    string private tokenDescription;
Хорошо 👍 только теперь нужно не потерять значения для description токена и контракта, которые раньше были. Можно в коде деплоя их сетить сразу после.

2023-10-20 20:28 UTC, nikitaGetman commented on config/metadata/nft_attributes.json
> +      "timestamp": "1697472000000"
тут таймстемп с учетом обычного года, нет 29 февраля. Лучше тогда от 2020 года считать.
Вообще пожалуй можем просто номер дня в году хранить (в високосном)
То есть: 1 января будет = 0,  20 января = 19, 29 февраля = 59.

2023-10-20 20:28 UTC, nikitaGetman commented on config/metadata/nft_attributes.json
> +      "timestamp": "1697472000000"
Можешь оставить как есть, но потом надо будет делать метод для определения дня рождения, хз насколько удобнее с таймстемпом.

2023-10-20 20:28 UTC, nikitaGetman commented on config/metadata/nft_attributes.json
> +      "timestamp": "1697472000000"
И проверь что дата точно верная, https://www.unixtimestamp.com/ показывает 16 октября для данного таймстемпа. Для простоты считай все в UTC часовом поясе (то есть +00)

2023-10-27 09:13 UTC, nikitaGetman approved these changes

2023-10-27 11:22 UTC, merged