AvatarSettings contract created
iSaver-io/isaver-contracts pull request #50
Opened 2023-12-14 09:48 UTC by GolubevDS

2023-12-14 13:16 UTC, nikitaGetman requested changes

2023-12-14 13:16 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +    mapping(address => uint256[]) private userActivePowers;
Не понятно зачем нужен userActivePowers. Кажется достаточно маппинга activePowers (можно переименовать в userPowers), который хранит время завершения подписки (либо 0 если подписка не была еще активирована)

2023-12-14 13:16 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +        emit AvatarActivated(_msgSender(), tokenId, collectionAddress);
Давай добавим ивент: ExternalAvatarActivated(sender, tokenId, collection) - если активирован аватар сторонней коллекции, AvatarActivated(sender, tokenId) - будет только для аватаров коллекции Avatars, PowersAccessActivated(sender) - когда активирован доступ к суперсилам (только если аватар был сторонней колекции)

2023-12-14 13:16 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +        if (avatar.collection != contractManager.getAvatarsAddress()) {
При установке аватара сторонней коллекции, доступ к суперсилам активируется один раз для всех сил, после активации доступа можно устанавливать любое количество сил, до момента деактивации аватара.

2023-12-19 02:59 UTC, GolubevDS commented on contracts/AvatarSettings.sol
> +    mapping(address => uint256[]) private userActivePowers;
userActivePowers нужен исключительно для перебора при деактивации суперсил.
Без него не получится по простому сбросить суперсилы у пользователя.

2023-12-24 09:25 UTC, nikitaGetman requested changes

2023-12-24 09:25 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +    mapping(address => uint256[]) private userActivePowers;
Можно просто сделать хардкодом, количество суперсил в ближайшее время не будет меняться, если что обновим контракт:
```
activePowers[_msgSender()][0] = 0
activePowers[_msgSender()][1] = 0
activePowers[_msgSender()][2] = 0
activePowers[_msgSender()][3] = 0
```

2023-12-24 09:25 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
>          emit PowerActivated(_msgSender(), powerId, block.timestamp + POWER_DURATION);
Тут нужно взять время из  `activePowers[_msgSender()][powerId]` так как может быть продление подписки

2023-12-24 09:27 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +    mapping(address => uint256[]) private userActivePowers;
Можно просто сделать хардкодом, количество суперсил не будет меняться ближайшее время, если что - обновим контракт:
```
activePowers[_msgSender()][0] = 0
activePowers[_msgSender()][1] = 0
activePowers[_msgSender()][2] = 0
activePowers[_msgSender()][3] = 0
```

2023-12-24 10:00 UTC, nikitaGetman requested changes

2023-12-24 10:00 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +
еще `__Pausable_init()`

2023-12-24 10:08 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +
В `AvatarsSell.sol` тоже надо добавить)

2023-12-24 11:05 UTC, nikitaGetman requested changes

2023-12-24 11:05 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +import "@openzeppelin/contracts-upgradeable/token/ERC1155/IERC1155Upgradeable.sol";
Этот импорт нужен?

2024-01-21 15:15 UTC, nikitaGetman requested changes

2024-01-21 15:15 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +            currentTimestamp >= birthdayThisYear && currentTimestamp < birthdayThisYear + 30 days;
Давай `30 days` вынесем в настраиваемый админом параметр

2024-01-21 15:15 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +        birthdayPrizesPool.getPrizeFromOracleRandom();
Вообще приз на день рождения будет определяться без запроса случайного числа в оракле. То есть приз будет получен сразу в транзакции запроса (при вызове `birthdayPrizesPool.requestPrize(...)`), поэтому статус isRequested не нужен. И достаточно одного метода для пользователя

2024-01-21 15:15 UTC, nikitaGetman commented on contracts/AvatarSettings.sol
> +    mapping(address => BirthdayPrizeInfo) private birthdayPrizeInfos;
Тут надо мапить по tokenId Аватара, так как приз должен быть один для Аватара, а не для пользователя. То есть пользователь сможет установить другой аватар, у которого сейчас ДР и получить второй подарок. А вот если для данного аватара уже получали подарок в этом году, то другой пользователь став владельцем этого токена не должен иметь возможности повторно получить приз

2024-02-01 13:59 UTC, merged